ideaData = [
    {
        openIDEOid: "C-001",
        content: "Bringing Transparency to the People: " +
            "How can we help provide information, education and transparency to the electronics supply chain – so that consumers make more informed decisions? ...",
        moreInfo: ["Bringing Transparency to the People", 
                   "How can we help provide information, education and transparency to the electronics supply chain – so that consumers make more informed decisions?",
                   "Today Today at IDEO Palo Alto we hosted an E-Waste Challenge brainstorm (using the Brainstorm in a Box toolkit).",
                    "We started by talking through the question of what e-waste is – and found that many people had different definitions of it. How might we help people understand where their electronics come from, what materials go into them, and how to reuse or recycle them when they're done?", "One idea we had was to create a website that helps anyone – kids, teachers, interested computer fans – how to dismantle and reuse their electronics safely. Maybe this website could even be a clearinghouse or catalogue where you could look up a specific product and how to take it a part or reuse it?", "We also thought we could leverage online platforms to help people share their own stories of creative reuse and recycling, like an e-waste hall of fame. Maybe we could even get celebrities to add their own stories!", "Finally we thought through how electronics packaging might also help bring transparency to the e-waste supply chain. Maybe a computer box could have a map that shows where its parts came from, and what consumers could do after they're done with it? Or the box could even have a prompt about how to turn your old stereo into a flower pot, a toy or clock!", "What other ways can we help educate consumers to better understand their role in the e-waste lifecycle?"],
        likes: 3,
        comments: 6,
        authorName: "IDEO Palo Alto",
        timestamp: "July 28, 2012, 12:45AM",
        views: 251,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/bringing-transparency-to-the-people",
        clicked: true
    },
    {
        openIDEOid: "C-002",
        content: "Build a DIY community to recycle e-waste: " +
            "E-Waste has a defining feature that sets it apart from all other types of waste... and that is its growing potential. What people need is a strong community of designers that can help ordinary people turn their electronic trash into treasure....",
        moreInfo: ["Ideally, we would like to find a way that our old devices don't end up in trash heaps or landfills-- damaging our environment as well as our health. What better way to get in touch with the wonders of technology by reusing old electronics to design new knick-knacks, gadgets, or art pieces? What we need is an accesible way to know what is safe to touch, twist, cut and use in new, exciting projects as well as what needs to go into safe receptacles. By building a DIY community of people of all walks of life who can sort out the valuable pieces of e-waste from the dangerous ones - we can not only safely design and innovate, but also advocate for the safe disposal and recycling of our old electronics.",
        "How does your concept safeguard human health and protect our environment?",
        "This concept reduces the amount of e-waste going into the trash and encourages people to reuse their waste in safe ways to do cool projects or revive old electronics. This should also teach everyday people what is safe to reuse and what isn't, and why. By highlighting the safety hazards of e-waste, it would remind users that these electronics do not belong in a regular trash bin.",
        "Where does your concept fit into the lifecycle of electronic devices?",
        "This concept embraces the afterlife and reincarnation of everyday devices into new innovative ideas. It encourages users to look at technology differently by realizing its incredible abilities as well as its potential. It should also get ordinary people who like to play and build interested on how certain technology works and how to reverse engineer and design some innovative products.",
        "What steps could be taken today to start implementing your concept?",
        "Designers, engineers, and any curious takers could begin documenting and designing new products and art from their old gadgets and together build an accessible community with all the right tools to bring out the designers in everyone.",
        "What kinds of resources will be needed to fully implement and scale your concept?",
        "In order to fully implement the concept, we would need a way to get in touch with the other DIYers out there to start building this collaborative. A website or forum would most likely be the best way to do this. This would take some time, a bit (but not too much!) money, and a little creative juices to get started."],
        likes: 6,
        comments: 6,
        authorName: "Kelly Hering",
        timestamp: "July 17, 2012, 03:34AM",
        views: 637,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/build-a-diy-community-to-recycle-e-waste",
        clicked: false,
    },
    {
        openIDEOid:"C-003", 
        content: "BuyCycle: If you want to buy (a)new, pay your due. (Or buy refurbished instead.) ...",
        moreInfo:["BuyCycle: If you want to buy (a)new, pay your due. (Or buy refurbished instead.)",
            "This may sound unusual &amp; \"interventionist\" at first, but once you think about it, it's actually not asking for much: People who want to buy a new device could be required to return (\"buycycle\") an old one in order to be granted the right to purchase.",   
            "The summary pretty much says it all already. You want to buy a new electronic device? Here are your choices:",
                "/t 1. Either return (\"buycycle\") an old one to acquire the right to buy new, or: ",
                "/t 2. Buy a refurbished/recycled one instead.",
            "(The old device wouldn't have to be the customer's most recent one, nor would it need to have been in his or her possession. Any old device is fine.)",
            "Implementing these conditions of purchase by law then would have several positive effects:",
            "\t It would make sure that discarded devices would rather promptly find their way back into the market – rather than waste their huge economic and ecological potential getting buried in some drawer somewhere.",
            "Put differently, people who up to now tended to keep and \"collect\" old cell phones for example (be it out of laziness, for hoarding goods or because they're not sure how and where to recycle them), wouldn't suffer any loss, but would be effectively incentivized to feed those devices' remaining economic and ecological potential back into the market.Those customers who keep using their phones for years and years could additionally be rewarded with special discounts, as suggested in Marie No's \"Hold on to your device and save!\" concept: http://www.openideo.com/open/e-waste/concepting/hold-on-to-your-device-and-save-the-green-deposit-system-for-newly-purchased-electronicsFirst-time product buyers would simply trade in unused devices from one of their friends or family members, thus actively helping to get those back into usageThe cost of this measure/incentive then would only be payed for by _those_ customers who decidedly want to buy the newest technology, although they still own very recent/valuable technology that they otherwise would have sold. (They could still try to trade in some very old and cheap device and sell their valuable one on the market, but due to the massive return flow of \"buycycled\" used phones into the retail market, even those market prices would be likely to drop significantly.)...which would also prove advantageous to the underprivileged people, who so far have had trouble to afford a cell phone for example in the first place, but could now benefit from the big supply and dropping prices of recycled and refurbished devices on the market.Lastly, this might even affect the prices for the new, cutting edge technology which would now face a relatively increased competition with relatively cheap but still valuable \"buycycled\" devices.",
            "(Sorry if I sketched this out rather apodictically. This is definitely more like a thought experiment. I'm not an economist, and especially the last three points are undoubtedly very speculative on my part. Even more so, I'd be happy to hear what other more economically-versed people think about my two cents here...)",

            "What steps could be taken today to start implementing your concept?",
            "Well, obviously it would take a number of steps in figuring out how to legally, logistically and economically implement the \"buycycle\" market. Much expertise and planning would be needed here: Who would \"own\" the \"buycycled\" devices? The state? The people? How would they be processed, how exactly returned into the market – and where? How exactly can the regulation be enforced? Might there eventually be a scarcity of \"buycyclable\" devices? If so, then how would the regulatory measure need to be adjusted? How can one make sure that the \"buycycle\" market is fair, transparent and can't be cheated? ...;",
            "A lot to think about, but maybe worth the effort? =)",

            "What kinds of resources will be needed to fully implement and scale your concept?",
            "Certainly a rather big interdisciplinary think tank of experts: economists, politicians, consumerists, legal advisers, environmentalists, manufacturers and technical experts (just to name a few...). Still, as I mentioned before, the regulatory mechanism itself could be pretty straightforward eventually."],
        likes: 5,
        comments: 13,
        authorName: "Hannes Mandel",
        timestamp: "August 12, 2012, 10:55PM", 
        views: 528,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/buycycle-if-you-want-to-buy-anew-pay-your-due.-or-buy-refurbished-instead.",
        clicked: false
    },
    {
        openIDEOid:"C-004",
        content: "chargers and cords exchange box ...",
        moreInfo: ["chargers and cords exchange box",
                   "This box is designed for a drop-off for cords and chargers and to be placed in local stores and shops. People can bring in their chargers for their old phones or cords that they no longer need to drop them off at the box for others who may need them.",
                   "Through our survey, we found out that most people have more than one old or broken phone they keep at home. It made us wonder what people do with their chargers and cords for their broken electronics. Inspired by IKEA's Missing a Part shelf (See image 2), our team came up with this cord-and-charger exchange program idea. We found this idea suitable for some local coffee shops that functionmore like a community, such as Cafe Paradiso (see image 3), where you can find items created by local artists for sale.",
                   "How does your concept safeguard human health and protect our environment?",
                   "This concept is very simple yet it creates an opportunity for the community to be \"green\" in an easy way. Fewer cords and chargers will end up in our landfill when they are still in working condition. This solution also avoids the purchase of new chargers when people lost their own ones.",
                   "Where does your concept fit into the lifecycle of electronic devices?",
                   "This concept encourages consumers to change their recycling behavior, giving them a convenient and simple place to recycle products in their own communities. It also encourages them to change their purchase behavior, giving them a free option to purchasing new cords/chargers/adapters when they need one, which can help reduce the e-waste that end up in landfills.",
                   "What steps could be taken today to start implementing your concept?",
                   "UPDATE: We have been in contact with Cafe Paradiso and they are interested in piloting our solution! Inspired, we dug down and tried to articulate the value and appeal of our solution to local businesses like Cafe Paradiso. Please see Image 4 above for our business and scaling model. &#13;",
                   "In this model, we have \"pivoted\" from our initial concept of a charger exchange box to a charger borrowing box. In this view cafes, for example, would be providing a service to their customers who do not want to bring chargers to the cafe, or who may have forgotten theirs at home. The value proposition to these businesses is the potential to bring in more customers and to keep customers at the shop for longer periods of time. What we would provide then is a simple, attractive, well-organized box integrated into a larger system. For example, the box would ship with stickers the cafes could display on their windows for advertising the new service. We would also serve as a place businesses could ship extra chargers for a recycling kickback or for repair.&#13;",
                   "Pricing and cost structure could either be some sort of markup per box, or a rental model, where businesses pay either a flat fee or a percentage of whatever sales increases could be attributed to the charger box (we could provide these metrics as a service). &#13;",
                   "Almost all of these aspects of the model currently stand as hypotheses that we would work to validate and iterate on in partnership with Cafe Paradiso and other small businesses in our community.",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "Our team is able to take this concept to manufacture stage without spending any cost on human resource. We also think that collection boxes can be made out of recyclable material, such as cardboard boxes, to enhance the effectiveness of the design. After the concept is well designed, we will need funding to manufacture the boxes and places to display these boxes. After the boxes are installed, our team is also able to take care of the advertising part using the various talents available in DFA UIUC community."],
        likes:      37,
        comments:   16,
        authorName: "DFA UIUC",
        timestamp:  "July 26, 2012, 12:51AM",
        views: 1237,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/chargers-and-cords-exchange-boxhttps://challenges.openideo.com/challenge/e-waste/winning-concepts/chargers-and-cords-exchange-box",
        clicked: false
    },
    {
        openIDEOid: "C-005",
        content: "Close the loop (discount for returned phone): " +
        "With every cell phone that you purchase you will receive a reply paid box in which you can send it back to the manufacturer...",
        moreInfo: ["Close the loop (discount for returned phone)",
                   "With every cell phone that you purchase you will receive a reply paid box in which you can send it back to the manufacturer.",
                   "With every cell phone that you purchase you will receive a reply paid box in which you can send it back to the manufacturer.",
                   "Benefit for Mother Nature: Less e-waste",
                   "Benefit for customer: When you sign up to Brand X's recycle program and return your phone you will receive a discount for your next purchase. Facebook post from company that gives customer\"green status\".",
                   "Benefit for brand/company: This could develop into a international competition in which brands try to be the best at their recycling efforts. Brands can build databases",
                   "How does your concept safeguard human health and protect our environment?",
                   "It encourages customers to send back their e-waste thus reducing world's e-waste.",
                   "Where does your concept fit into the lifecycle of electronic devices?",
                   "It encourages companies to build products from parts that could be used in future developments.",
                   "Companies could start a \"reuse competition\" where their designers build new products from recycled materials.",
                   "What steps could be taken today to start implementing your concept?",
                   "Convince companies of the benefits to their brand. Not hard in times of corporate philanthrophy?",
                   "Do some further work to understand what would encourage consumers to send back their old phones? Would they keep the reply-paid boxes for the lifetime of their phone or is there an alternative solution?",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "Communications materials",
                   "Awareness campaign",
                   "Reply -paid boxes",
                   "New company unit that deals with the returned phones",
                   "Company-internal solutions to recycle or re-use"],
        likes:      3,
        comments:   6,
        authorName: "Robert Homberger",
        timestamp:  "August 03, 2012, 05:50AM",
        views:      921,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/close-the-loop-discount-for-returned-phone",
        clicked: false
    },
    {
        openIDEOid: "C-006",
        content: "Connecting Users: " +
        "How can we help people connect + share their electronics to give e-waste items a second life?...",
        moreInfo:["Connecting Users",
                  "How can we help people connect + share their electronics to give e-waste items a second life?",
                  "Today Today at IDEO Palo Alto we hosted an E-Waste Challenge brainstorm (using the Brainstorm in a Box toolkit).",
                  "One common theme that came up for us was connections. How might we enable people to come together, pass on the electronic items they're no longer using, or make use of a second-hand item that's new to them?",
                  "It started with the idea of a swap meet for e-waste; people bringing all their functioning, previously-used items to trade with others. We explored the idea of a 'Bits + Pieces' day at work, where people could bring in their old items, components, chargers etc and donate them to other coworkers who could use them.",
                  "Then we explored the donation concept further and talked about how current programs help recycle cell phones, for instance, for military veterans or women's shelters. What if we could match up a 'person in need' of a cell phone, for instance, with one that's no longer needed for another person?",
                  "What if people traveling to other countries could pack in their luggage two or three small, used electronic items to donate to people who could use those them next?",
                  "What if every phone, laptop or other electronic gadget came with a prepaid envelope to send it on to someone else once you were done using it?",
                  "Do these questions about connections spark any ideas for you?"],
        likes:      1,
        comments:   4,
        authorName: "IDEO Palo Alto",
        timestamp:   "July 27, 2012, 10:56PM",
        views:       264,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/connecting-users",
        clicked: false
    },
    {
        openIDEOid: "C-007",
        content: "Create a high quality media campain & educational program for schools to develop sustainable habbits ...",
        moreInfo:["Create a high quality media campain &amp; educational program for schools to develop sustainable habbits",
                  "To raise the public awarenss of the people through the local and social media, to give them ideas how they personally can create a positive envoirmental impact (in cooperation with goverments, green NGOs, green WM buisneses, and schools)",
                  "Main slogan : little actions - big impact",
                  "To be really effective that kind of project should be result of cooperation of prof. psychologists, ecologists and media experts.",
                  "Main goals:",
                  "    1 create a bright message of e-waste problem through the media" +
                  "    2  teach people about products LCA" +
                  "    3  provide a pesonal solution (if you not part of solution you are part of the problem)" +
                  "&nbsp &nbsp &nbsp &nbsp '4 inspire people to take a green action (become a part of solution)'" +
                  "<br> '5 create a great e-WM campain in cooperation with big electronic companies'" +
                  "6 to develop a highly effective WM educational program for schools with will help kids to develop a sustainable habbits",
                  "How does your concept safeguard human health and protect our environment?",
                  "I really like that quote: Often we asks with planet our kids will inherit, but better to ask with kids will inherit our planet..It is our responsibility to grew the generation with sustainable values and sustainable habbits.",
                  "If we will sucseed in that area our planet might have future.",
                  "Where does your concept fit into the lifecycle of electronic devices?", 
                  "It will envourage people to think about consicuenses and it will be norm and habbit to act responsibly.",
                  "What steps could be taken today to start implementing your concept?",
                  "My friends in Svitzerland already developing LCA and clear impact picture for over 200 green habbits.",
                  "Im establishung contacts with proffecional psychologists to help us to decelop a simple step by step geshtalt model with help everyone in new habbit development.",
                  "The counsil of my city and the managers of OCSE Green Pack poject are interested in cooperation with us on that project.",
                  "What kinds of resources will be needed to fully implement and scale your concept?",
                  "we need to gether a team of preffesionals with burning hearts",
                  "envoirmentalists, psychologists, celebrities, local athorities and advert experts",
                  "we will need a couple prof. designers to make high quality social ads and illustrations for products LCA",
                  "we will need to find some sponsors to run green actions and competitions in the schools",
                  "and we will need to find finnance to pay specialists for they work"],
        likes:      3,
        comments:   1,
        authorName: "Valentina",
        timestamp:  "August 11, 2012, 09:29PM",
        views:      288, 
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/create-a-high-quality-media-campain-educational-program-for-schools-to-develop-sustainable-habbits-d1",
        clicked:    false
    },
    {
        openIDEOid: "C-008",
        content: "Create E-waste Awareness Through A Rubbish Tracking System ...",
        moreInfo:["Create E-waste Awareness Through A Rubbish Tracking System",
        "As a method of generating awareness to the long lifespan of electronic products, i suggest that a number a different electronic products are taged with an global positioning device in order to track their movements around the world over a lifetime.",
        "As a method of generating awareness and gathering information about the long lifespan of electronic products, i suggest that a number a different electronic products are taged with an global positioning device in order to track their movements around the world over a lifetime. In theory, tracking a number of devices would show the origins of the device (China, maybe) followed by a number of years of spiratic movement around a small area or city will occasional long distance travel. Finally the product would be replaced by a better, newer model and the old device would remain stationary and unused.  It is this final destination that holds that most important data. Is the final resting place in someones home? is it in land fill? Have they given the device to someone else (sold it or given it away)?",
        "How does your concept safeguard human health and protect our environment?",
        "This concept provides important information about what consumers do with their device when they replace it. The information recorded could offer a great incite that could be used in advertising campaigns to encourage users to dispose of their devices in a way the protects our environment. For example, if the date recored that the majority of people kept their old mobile phones in their homes after they had upgraded to another one. A advertising campaign could be targeted to \"get your phone out of the draw and into the phone recycler\".", 
        "Where does your concept fit into the lifecycle of electronic devices?",
        "It monitor the entire life cycles from a global positions perspective.",
        "What steps could be taken today to start implementing your concept?",
        "Find electronics company's that are willing to provide external organisation with this information.",
        "Find consumer groups that are willing to participate.",       
        "What kinds of resources will be needed to fully implement and scale your concept?",  
        "-GPS tracker small enough to fit in a mobile phone or similar device;",
        "-Software program to record the data",
        "-staff to analysis the date",
        "-electroics companies or consumer groups willing to particitpate"],
        likes:      6,
        comments:   2,
        authorName: "Michael Smith",
        timestamp:  "August 10, 2012, 03:06AM",
        views:      734,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/create-e-waste-awareness-through-a-rubbish-tracking-system",
        clicked:    false
    },
    {
        openIDEOid: "C-009",
        content: "Design with the end in mind: " +
        "What if products were designed to have  a beneficial/zero impact on the environment at end of life cycle? ...",
        moreInfo:   ["Design with the end in mind.",
                     "What if products were designed to have  a beneficial/zero impact on the environment at end of life cycle?",
                     "The lifecycle of electronic equipment needs to be transparent and easy to understand.  By simple, I mean something that a grade school child would understand. The lifecycle could be something as simple as being biodegradable or plantable at the end of use. ",
                     "How does your concept safeguard human health and protect our environment?",
                     "Because the design has either a zero or positive impact on the environment, we all benefit.  ",
                     "Where does your concept fit into the lifecycle of electronic devices? ",  
                     "My idea fits in the beginning.  I think the incentives financially motivate manufacturers and consumers are motivated by status, eco consciousness or both.  ",
                     "What steps could be taken today to start implementing your concept? ",
                     "I would create a mastermind group of technical people that know what is currently possible, chemists for what could be possible, creatives for design and for promoting and getting the entertainment industry involved (several champions), government types that have made things happen in the past, key businesses and influential bloggers.  A futurist or two like Jacques Fresco would also be great.  ",
                     "What kinds of resources will be needed to fully implement and scale your concept?",
                     "To properly motivate manufacturers I think a diversified approach would work best. Financial incentives help businesses in the immediate term. Progressive and business friendly governments can help attract new business to their region by offering tax incentives for offering this kind of manufacturing. In turn, the governments benefit from a larger tax base and lower unemployment.",
                     "I think these type of electronics would have major status appeal for both the manufacturer and the consumer. The second part of the strategy would be to engage the entertainment industry (those that are pro-environment).",
                     "Why not take an area like Detroit and approach industry leaders with this idea?  http://detroitventurepartners.com.  Their region has a history of innovation,  culturally the people are acclimated to being a manufacturing hub and politically, the will might be there.  "],
        likes:      6,
        comments:   6,
        authorName: "Christine Thompson",
        timestamp:  "August 09, 2012, 12:02AM",
        views:      319,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/design-with-the-end-in-mind.",
        clicked: false
    },
    {
        openIDEOid: "C-010",
        content: "Devices and Lifetime, Government Incentives: " +
        "A project to create norms and standards, creating a model of quality and sustainability.",
        moreInfo:["Devices and Lifetime, Government Incentives",        
                  "A project to create norms and standards, creating a model of quality and sustainability.",
                  "This concept was generated in the AIESEC brainstorm last month. We were invited to take the e-waste challenge to a group of graduate students from AIESEC (http://www.aiesec.org.br/). There were almost 80 students bringing ideas to the challenge. We used the Brainstorm in a Box toolkit adapted. It was very exciting and we proudly share one of the concepts generated here.",
                  "This concept was generated in the AIESEC brainstorm from the challenge:", 
                  "How can we design electronic devices built to last?",
                  "A project to create norms and standards, creating a model of quality and sustainability through software upgradeable and modular components, rewarding companies that have achieved this standard of quality, protecting it from those who do not use this model."],
        likes:      3,
        comments:   1,
        authorName: "ItaÃº Unibanco",
        timestamp:  "August 09, 2012, 03:04PM",
        views:      129,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/devices-and-lifetime-government-incentives",
        clicked: false
    },
    {
        openIDEOid: "C-011",
        content: "Devices and Lifetime, Modular Designs and Production Line: " +
"Design modular parts to create electronic devices...",
        moreInfo:["Devices and Lifetime, Modular Designs and Production Line",
                  "Design modular parts to create electronic devices. ",
                  "This concept was generated in the AIESEC brainstorm last month. We were invited to take the e-waste challenge to a group of graduate students from AIESEC (http://www.aiesec.org.br/). There were almost 80 students bringing ideas to the challenge. We used the Brainstorm in a Box toolkit adapted. It was very exciting and we proudly share one of the concepts generated here.",
                  "This concept was generated in the AIESEC brainstorm from the challenge: ",
                  "How can we design electronic devices built to last?",
                  "Mounting device for modules for easy replacement of parts and not from the entire device. Creation of simple devices and adaptable to changing parts.",
                  "Use of recycled materials and more durable batteries.",
                  "Research on the most common fails on devices. Repair of the pieces by the manufacturer facilitating discards of products and redistribution of old devices. "],
        likes:      2,
        comments:   1,
        authorName: "ItaÃº Unibanco",
        timestamp:  "August 09, 2012, 02:51PM",
        views:      164,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/-devices-and-lifetime-modular-designs-and-production-line",
        clicked: false
    },
    {
        openIDEOid: "C-012",
        content: "Devices and Lifetime, Update and Reuse: " +
        "Government and Itaú investing in development projects with universities of technology.",
        moreInfo:["Devices and Lifetime, Update and Reuse",
                  "Government and Itaú investing in development projects with universities of technology.",
                  "This concept was generated in the AIESEC brainstorm last month. We were invited to take the e-waste challenge to a group of graduate students from AIESEC (http://www.aiesec.org.br/). There were almost 80 students bringing ideas to the challenge. We used the Brainstorm in a Box toolkit adapted. It was very exciting and we proudly share one of the concepts generated here.",
                  "This concept was generated in the AIESEC brainstorm from the challenge: ",
                  "How can we design electronic devices built to last?",
                  "Government and Itaú investing in development projects with universities of technology related to the topic:",
                  "- Technological studies to create parts of devices that can be exchanged",
                  "- Studies in software product update avoiding disposal.",
                  "Companies that use this technology in their products, have tax incentives from the government also be recognized by Itaú."],
        likes:      1,
        comments:   0,
        authorName: "ItaÃº Unibanco",
        timestamp:  "August 09, 2012, 02:25PM",
        views:      125,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/devices-and-lifetime-update-and-reuse",
        clicked: false
    },
    {
        openIDEOid: "C-013",
        content: "Devices and Lifetime, Versatility: " +
        "Create versatile products, easy to upgrade (free software in common use at all and that everyone can add new features) and wide range of use.",
        moreInfo:["Devices and Lifetime, Versatility",
                  "Create versatile products, easy to upgrade (free software in common use at all and that everyone can add new features) and wide range of use.",
                  "This concept was generated in the AIESEC brainstorm last month. We were invited to take the e-waste challenge to a group of graduate students from AIESEC (http://www.aiesec.org.br/). There were almost 80 students bringing ideas to thechallenge. We used the Brainstorm in a Box toolkit adapted. It was very exciting and we proudly share one of the concepts generated here.",
                  "This concept was generated in the AIESEC brainstorm from the challenge: ",
                  "How can we design electronic devices built to last?",
                  "To address this question, the students had the idea to create versatile products, easy to upgrade (free software in common use at all and that everyone can add new features) and wide range of use.",
                  "These products were made​​ with parts whose repair was easy and that his replacement also recyclable and durable materials."],
        likes:      1,
        comments:   0,
        authorName: "ItaÃº Unibanco",
        timestamp:  "August 09, 2012, 02:16PM",
        views:      114,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/devices-and-lifetime-versatility",
        clicked: false
    },
    {   
        openIDEOid: "C-014",
        content: "Digital data transfer and elimination service",
        moreInfo:["Digital data transfer and elimination service ",
                  "At the end of a mobile phone's (first) life a data transfer and elimination service will encourage users to hand in their old phones to be re-used, re-furbished or re-cycled without having to worry that personal data is either lost or misused.",
                  "Take-back schemes for electronic gadgets such as mobile phones do exist but despite financial incentives uptake has been slow. One issue is that users have data on devices that they either cannot transfer to a new gadget or the worry that personal data left on the device could be misused by a third party. The proposed digital data transfer and elimination service could be offered by phone retailers. The benefits for retailers include creating a stronger 'green' corporate image, access to resources that can either be re-used or recycled and potential customers looking for a new phone. ", 
                  "How does your concept safeguard human health and protect our environment?",
                  "The system encourages increased uptake of mobile phone take-back schemes.",
                  "Where does your concept fit into the lifecycle of electronic devices? ",
                  "End of (first) life/ re-use. However, if the service is widely implemented, it might encourage manufacturers to design phones for disassembly and re-use. This would follow a similar model to disposable cameras that are handed in to develop films where they are collected and returned into the production cycle. ",
                  "What steps could be taken today to start implementing your concept? ",
                  "• User survey to test and quantify the theory that people are less likely to give away their old phones because of personal data stored on the device.",
                  "• Partner with a mobile phone retailer to test the service",
                  "• Feedback from everybody here",
                  "What kinds of resources will be needed to fully implement and scale your concept?",
                  "1) Literature review or user survey to test the theory (6 weeks, someone to do the work, money to fund the initial review)",
                  "2) Partnership with mobile phone retailer to develop and test the service (3 months, money, design team)",
                  "3) Launch the service (6 months, money for advertising campaign, launch event, technology, design teams)",
                  "4) Evaluate, disseminate findings (1 year, team of analysts, bloggers, etc.)"],
        likes:      30,
        comments:   10,
        authorName: "Anne Schiffer",
        timestamp:  "August 14, 2012, 03:01PM",
        views:      663,
        url:        "https://challenges.openideo.com/challenge/e-waste/concepting/digital-data-transfer-and-elimination-service-",
        clicked: false
    },
    {
        openIDEOid: "C-015",
        content: "Disassembly Time Tax: " +
        "Taxing electronics based on the time it takes to separate toxic materials containing parts from the rest.",
        moreInfo: ["Disassembly Time Tax",
                   "Taxing electronics based on the time it takes to separate toxic materials containing parts from the rest.",
                   "Separating toxic parts from normal materials, such as plastic covers, is often difficult and time consuming. Electronic devices could be taxed based on the time it takes to separate parts containing toxics from the rest. Tax could be a fixed amount tax times the time in seconds it takes to disassemble the device. This way the well-designed modular devices could avoid the tax almost completely. At the same time the modularity might make the production of devices easier, thus providing the companies also cost savings. As a result, the companies would have financial incentives to design easily recyclable devices.",
                   "UPDATE:",
                   "Environmental ratings (see also recy-cool-ability by Paul) could be used to define the amount of tax for different devices.  The better the rating, the lower the taxes. A similar tax has also been suggested by Priscilla. These kind of taxes would create  new design constraints helping to implement concepts by Valentina and Christine, which would, among other things, encourage development of modular cell phones. Modular cell phones would support the creation of new business models, such as rewire.com by Andrew. The second photo is a simple illustration of the relationships between all these concepts",
                   "Thanks, Paul, again for the suggestions!", 
                   "How does your concept safeguard human health and protect our environment?",
                   "The recycling of e-waste would be made more efficient by making it easier to separate toxic internal parts of electronic devices from non-toxic covers. ",
                   "Where does your concept fit into the lifecycle of electronic devices? ",
                   "The concept fits both to design phase of new electronic devices and processing of electronic waste. The tax would create incentives to design devices that are easier to process at the end of their life-cycle.",
                   "What steps could be taken today to start implementing your concept? ",
                   "Lobbying politics.",
                   "UPDATE: The finished concept could be posted to sites aimed at crowdsourcing law propositions from citizens. These kinds of platforms and supporting legislation are already in place in some countries. One example is described here: http://blog.microtask.com/2012/05/welcome-to-the-open-ministry/",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "Most important resource is the political will to implement a new tax. ,"],
        likes:      7,
        comments:   12,
        authorName: "Juho Salminen",
        timestamp:  "August 12, 2012, 05:19PM",
        views:      493,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/disassembly-time-tax",
        clicked: false
    },
    {
        openIDEOid: "C-016",
        content: "Don't Debate, Granulate!: Turning e-Waste into Rugged Building Materials",
        moreInfo: ["Don't Debate, Granulate!: Turning e-Waste into Rugged Building Materials",
                   "There is an unconventional and seemingly unexplored solution to managing the dilemma of non-biodegradable (and often, hardly reusable) e-waste. Pulverize it into a fine powder and mix that product with an epoxy resin, then shape it into bricks.",
                   "There are a number of issues involved with trying to disassemble electronic devices and 'de-articulate' their specific components.  However, it would seem that the main roadblock preventing more recycling agencies from wanting to invest in e-waste recycling initiatives is simply that the effort is generally not profitable.  There are, on the other hand, a small number of companies who use machines called Super Granulators (essentially, giant rock tumblers with enormous crushing power) to grind down electronic components (and other non-biodegradable bulk materials) into more compact versions of the same waste; this is done both in the US and abroad.  My idea is this: use Super Granulators to completely pulverize e-waste into a fine powder and then mix that product with an epoxy resin.  Provided that the powder is of a fine enough grade, this slurry could be easily formed into extraordinarily durable bricks, pavement-like substances and other rugged building materials.",
                   "A typical computer motherboard is comprised of over twenty different materials.  When you granulate something (crush it into a sand-like substance; granulated sugar, for instance), you generally have little control over the exact size, shape and weight of the resulting sand-like pieces that are produced.  Both the variety in material (from all of the different electronic 'stuff' scrambled together) and the general inconsistency of granule size (from the lack of precise control from the crushing process) are actually beneficial aspects of my concept.  By mixing diverse granules together, you effectively create a structural matrix (two or more substances that contrast each other in terms of individual properties, but complement each other symbiotically when combined in one material) which has shared benefits from all of the ingredients that went into it.  You have probably seen the packing tape which has lines of string running through it which are very obnoxious to cut through and near-impossible to tear through--those strings strengthen the overall tape strip enormously (duct tape often has similar threads in it).  Using the diverse, pulverized debris would in many respects, do the same thing for the building materials.  The variety of tough, rigid and strong materials in computer parts is a plus.  The desirability for diversity among granules in building materials is also the reason why most cinder-blocks and paved roads have variously-sized chunks of different debris in them.  This is called an aggregate, and that is essentially what the e-waste dust would be; it would be the aggregate in the cement.",
                   "Now, it might not necessarily be a good idea to have 'one batch' of bricks made from only cellular phones (which have ABS and PVC plastic bezels/chassis, Lithium batteries, etc.) and another batch made solely from old televisions (Silica Glass, Vacuum Tubes, Rubbers, etc.).  Separating certain types of objects for different batches of building materials would defeat the purpose of having a maximum variety of different 'stuff' in the slurry.  However, certain batches might be able to benefit from having an abundance of one (or more) specific types of material.  Let's assume an affordable housing community was being constructed in a region particularly prone to harsh winters; let's take Reykjavik, Iceland, for instance.  In this case, making bricks or paving materials solely out of computer motherboards (or breadboards and mainboards of other electronics as well) and excluding speakers (for example) might be a smart decision.  The large amount of silver-based soldering materials and synthetics on the boards would give the bricks a denser property, which would be critical in a region where drastic climate change (and the expansion and contraction resulting from it) causes weaker materials (such as the rubbers, particle board and carbon papers commonly found in standard bookshelf speakers) to split and falter.  ",
                   "Taking this into account, let's consider the Adobe dwellings of the Ancient Pueblo Peoples.  These structures in the Southwestern United States which were crafted from sand, mortar and stone (and the many minerals which comprise these substances).  Structures like these have withstood the test of time in harsh climates the world over where temperatures can fall near freezing at night and soar into the hundreds by day.  These structures are made from the same stuff that computer parts are made from--sand: a granular aggregate consisting primarily of Silica (which comprises the green (or sometimes, brown) rectangular wafer that almost every electronic component today is built upon--hence the name \"Silicon Valley\").  Between the variety of materials in the infrastructure of solder and wiring and in the the network of ceramic diodes--computer parts contain a large number of minerals which exist in sand.  Using e-waste to construct a cement-like building substance would give the resulting material highly-desirable properties similar to those which the Ancient Pueblo Peoples put to their great advantage in their thermally-adaptable and rugged architectures.",
                   "What the Ancient Puebo Peoples effectively produced was essentially what is now referred to as a \"Trombe Wall\"--a wall which reflects sunlight during the day (because the Silica in sand acts like a glass mirror), but retains the heat which it does absorb and forces it into the structure at night.  This type of passive-solar technology is becoming more popular as a greater emphasis has been placed on ecologically-intelligent architecture.  Turning e-waste into building materials and using these materials to build walls on homes would effectively do the same thing as the sand that served this purpose in Ancient Pueblo building styles.  This is because of the large amount of Silicon in the computer chips.  Additionally, a paint could be made out of scrap motherboards which, if painted onto a wall in a thick coating and with a dense stone-like structure beneath it, would be able to do achieve same thing, to some effect.  Ironically, this would be an ideal way to recycle typical roof-mounted photovoltaic solar panels which have a lifespan, are difficult to recycle and contain a large amount of silicon, the primary platform in most currently-existing PV-cell units.",
                   "One additional point which should be taken into account is that there are in fact a number of valuable, and in some cases, rare elements which exist in computer parts of all types.  Elements such as Gold (which is used to prevent contact areas on computer parts from corroding) and Neodymium (a powerful magnetic element which enables us to have small speakers like those in ear buds and is also used as the writing agent in most non-solid-state hard disk drives) would certainly be worth trying to salvage from the scrap.  In fact, salvaging these types of materials from e-waste is probably the only reason that some companies are presently willing to take-on the task of recycling computers.  The problem with salvaging these materials is that they are, in many cases, extraordinarily difficult to separate from the rest of the scrap and it is often very time consuming (frankly computer towers specifically should be built to come apart more easily for recycling purposes so that they do not need to be pulled-apart meticulously by hand in order to salvage pieces).  Gold, for instance, is probably the most abundant material of high-value in an expensive electronic device.  However, it is generally electroplated onto contact points (like the copper connectors in a handheld video game cartridge or on the pins of a CPU processor) and getting the gold off of these small areas is a total pain in the neck.  The two common ways to do it are by reverse-electroplating the components (which causes the gold to peal away like gold leaf from the copper/brass/etc. underneath) of by creating an amalgam and boiling the gold off of the other parts with mercury.  Both of these methods are generally bad for the environment and only become profitable in a very large scale operation, which takes so much capital investment to procure that it is not something that interests many recycling agencies (especially in a poor economy when venture capitalists are far less likely to gamble on an up-start scrapping agency that won't return principal investment for another decade).",
                   "With this being said, there is hope for granulation.  By pulverizing the e-waste materials into a powder (Gold included), there become a number of new opportunities to separate certain types of materials.  By using a powerful electromagnet and 'churning' the powder with it, you can pull out any ferrous (magnetic) materials from the dry powder mix.  By heating the powder at different temperatures on a fine carbon screen (like an archaeologist's sifting tray) you can separate certain materials based upon their respective melting points.  For instance, lead-tin and silver solder (depending on their exact compositions) would melt at temperatures lower than 600F, so granules made of those substances existing in the powder would melt into an aqueous state and the liquid would fall through the grid and reconstitute on the lower side of the screen while leaving the other materials still in the dry powder.  Raise the temperature again and you can do that for another substance; the precision of the temperature will determine what elements and compounds will fall through the grid.  Naturally, you would start low in small increments and work your way up until you separate the gold alloys somewhere around 1650F.  You can also use a centrifuge to spin the powder at at an ultra-high velocity and separate granules by weight--this would effectively separate the metals from the non-metals with relatively little effort.  Additionally, you could also use liquids of differing densities (pour glycerin in a tank with a less-dense oil on top of it with water on top of that, for example) and pour the granules into the tank and they will separate into general categories depending on their respective densities (some materials will float on the water, some will be neutral in the oil and others will sink into the glycerin).",
                   "How does your concept safeguard human health and protect our environment?",
                   "The concept of granulating e-waste and using it as a basis for structural materials proposes great benefits over the current solutions for e-waste management in regard to the well-being of humans and the environment.  Aside from emissions resulting from transporting the scrap and the power used to granulate it, the main foreseeable issue with granulation in terms of environmental and human hazards is the release of ultra-fine airborne particles which may be released during granulation (microscopic pieces of silicon, etc.).  This is easily solvable with proper carbon filtration and electrostatic purification systems.  Research would need to be conducted in order to find (or create) a UV-resistant epoxy to mix the granules with that would be economically viable and leave a minimal carbon footprint (both in terms of manufacture and in what it might leech over time as it is exposed to the elements).  Many plastics (and glues especially) are not fabricated with sustainable methods and some manufacturing methods yield toxic by-products.  Surely, there are other alternative solutions to epoxy for making the powder-granule e-waste into a cement-like slurry and these alternatives might benefit from consideration and analysis.",
                   "Where does your concept fit into the lifecycle of electronic devices? ",
                   "The e-waste granulation concept is absolutely at the very end of the electronic device life cycle.  I personally think that if it were to (hypothetically) be enacted, that within a relatively short amount of time, a 'seal of approval' could be produced.  This seal might encourage electronics manufacturers to produce products that have certain types of materials in them, rather than others (for the goal of creating a better product for future granulation).  For instance, ABS plastic might be chosen for more applications in consumer electronics if the manufacter was aiming for a seal of approval; ABS has structural and thermal properties superior to more common types of consumer plastic (like PVC) and would therefore be a better ingredient in, say, a tile in the floor of a greenhouse.  Concurrently, I think that consumers might look for certain items with the 'seal of approval'--maybe consumers could get a discount on buying granulated e-waste building materials by cutting-out and saving the UPC codes from electronics that they had previously purchased which had the approval seal on their package at one time.",
                   "What steps could be taken today to start implementing your concept? ",
                   "I think that the first step that could be taken today, would be to contact some of the existing agencies which specialize in industrial-scale granulation.  It would be necessary to hash-out some of the possibilities for creating a usable product from granulated e-waste scrap to see how feasible the concept currently is and what could be done to make it a reality in the future.",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "Super Granulators are expensive machines (some cost millions).  They are generally custom-built and installed and require large factory-settings with proper ventilation.  It would certainly be better to try and work cooperatively with an agency that is already in the business of industrial granulation than to try and take-on the project from the ground-up.   The same is probably true for epoxy manufacturers--high-density plastics are not always cheap to manufacture and even some of the glues which are less-costly to make, still require specialized machinery.  This being said, it would probably be smart to initiate business relations with a glue manufacturer (of course, this would apply to cement as well, if that were deemed a more practical solution for the concept than epoxy resin)."],
        likes:      10,
        comments:   8,
        authorName: "Maximilian Kaiser",
        timestamp:  "July 16, 2012, 02:22AM",
        views:      369,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/don-t-debate-granulate-turning-e-waste-into-rugged-building-materials",
        clicked: false
    },
    {
        openIDEOid: "C-017",
        content: "Don't Upgrade, Go to the Cloud! " +
        "What if you never needed to upgrade any device but just keep moving memory and processing to the cloud? We introduce, the Eco-cloud-drive, an awareness program to move people and companies to the cloud to reduce consumption and costs.",
        moreInfo: ["Don't Upgrade, Go to the Cloud!",
                   "What if you never needed to upgrade any device but just keep moving memory and processing to the cloud? We introduce, the Eco-cloud-drive, an awareness program to move people and companies to the cloud to reduce consumption and costs.",
                   "A report issued this summer by the Carbon Disclosure Project, supported by AT&amp;T, finds that you can reduce energy consumption, lower carbon emissions and decrease expenditure on IT by moving to the cloud. By 2020, the group estimates, large US companies that use cloud computing can achieve annual energy savings of $12.3 billion and annual carbon reductions equivalent to 200 million barrels of oil. But unfortunately, right now, not many people know about the benefits of cloud computing or are afraid of it. How can we change that?",
                   "Another problem is that most of the devices we purchase today are over-powered. They're not based around our actual usage and instead focus on the technological capabilities, leading to expensive and mostly unnecessary devices that are marketed to create a sense of need. Could we instead keep our old devices but still expand our memory and processing on the cloud? What we need is a campaign to move people to the cloud. If we stop buying devices, they never get outdated. If they don't, e-waste will drastically reduce! Here are a couple of personas  and contexts to put it into perspective.",
                   "Jacques Chevelle is 48 years old and is the CTO of a mid-sized bank in Monaco. This year, they've had an increase in clients and that's good news. But unfortunately, their current IT systems are fast approaching load-saturation and they need to expand their capabilities. Only three months are considered to be busy and put a strain on the systems. Unfortunately, to be able to handle it, new mainframes need to be purchased. He contacts his current IT dealer and informs him of the expected peak load and gets a quote for full-rack servers that will cost him $1.4 million. The additional energy and cooling costs are calculated to be $120 K/year. In order to house it, it also costs real estate, new facilities and staff to maintain it. Fearfully, Jacques prepares the report to allocate the budget. Then, during his search, he stumbles on a Google ad that catches his attention. \"Looking to expand? Move to the cloud!\" Curious, he clicks on it and learns about the benefit of the cloud. The more he reads, the more he is relieved. He quickly tears up the report and prepares a new one. It's only going to cost him $30 K/month for 3 months to outsource his peak load to a virtual private cloud service. Not only does he save money, but also space, energy and resources.",
                   "My mom: My mom uses her old laptop just like most people: to browse the internet, send e-mails, watch movies, and Skype. Nothing resource-heavy. In fact, she never updated her OS since Windows XP as she was introduced to Ubuntu, which suits her needs and is free. But her one bad habit is that she hoards every single picture, song and video that she likes. The multiple GB's of data clog the laptop's memory and makes it sluggish. Now, it's slow and there's no more space for her stuff. Is it time for her to upgrade to a new device? While shopping online, she stumbles on an ad: \"Want to upgrade? Don't! Go green with cloud!\" She clicks on it and learns that she doesn't need a new $600 laptop, she can keep her old one and just put all her stuff on the cloud! (In real life, she got my brother to do it for her). Now, she just has to spend $30 a year and now has a clutter-free and unclogged laptop. Her laptop never became outdated.",
                   "This could soon be applied to mobile phones, tablets and laptops for individuals (Especially since technology will converge on that \"One device to rule them all\"). It could just as well apply to companies who upgrade their systems and dump large amounts of e-waste each year. By moving to the cloud, no device becomes outdated, it's not just storage, processing too can be outsourced so data-heavy applications would still be able to run on older devices. As long as they don't break, your devices will never get outdated. Hopefully, e-waste becomes history. Also, make sure you check out the video that inspired me where Louis CK predicts the future.",
                   "How does your concept safeguard human health and protect our environment?",
                   "As we move on from a product economy to a service economy, we can rely lesser on mining for metals to make devices, we can make sure that lesser devices are produced and more effort is taken on maintenance, lowering energy consumption and having products that have lesser impact on the earth's resources. ",
                   "Where does your concept fit into the lifecycle of electronic devices? ",
                   "This would definitely come under the design period of the product's life cycle.",
                   "But also considering constant updating and outsourcing of processing, it is also a continuous process that is in place that occurs throughout the usage period of the product.",
                   "What steps could be taken today to start implementing your concept? ",
                   "The first step would be to educate people and companies about the concept of cloud computing and start a dialogue about potential use scenarios in the future.",
                   "It is also important to inspire entrepreneurs to be able to build support services for products and inform large companies of the need that exist for these devices.",
                   "Also, it is important to let people know that cloud computing does not have as many security issues as the media claims and that its only going to get safer and more ubiquitous.",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "People: It is important to have people who are willing to switch to the cloud. This applies to individuals as well as large companies that are upgrading their legacy systems and end up buying more mainframes and rack processors. We need evangelists to talk to people and explain the benefits.",
                   "Partnerships: There needs to be more collaboration between large companies and the open-source developers community. A few companies like Samsung are starting to offer support and open API's to the general public to allow them to build better products and services around them. Perhaps we could start a conversation between the two communities.",
                   "Technology: Cloud developers! There are so many new companies cropping up in this fast-changing environment that it would be great to keep an eye out for new technology. Also, Google ads are a cheap and effective way to campaign."],
        likes:      16,
        comments:   8,
        authorName: "Ashwin Gopi",
        timestamp:  "July 21, 2012, 12:51AM",
        views:      539,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/don-t-upgrade-outsource",
        clicked: false
    },
    {
        openIdeoid: "C-018",
        content: "E-Cycle Truck: " +
        "How many people in your town, including you, know about e-cycling? Why is there a lack of awareness when the increasing amount of e-waste is a serious problem throughout the world? The E-Cycle Truck aims to educate and facilitate e-cycling!",
        moreInfo: ["E-Cycle Truck",
                   "How many people in your town, including you, know about e-cycling? Why is there a lack of awareness when the increasing amount of e-waste is a serious problem throughout the world? The E-Cycle Truck aims to educate and facilitate e-cycling!",
                   "The idea of the E-Cycle truck is to promote and inform people about the importance of e-cycling as well as provide a convenient place to recycle or repair old electronics. Inspired by the food truck movement, the E-Cycle truck (appropriately, a repaired and transformed old truck) would go around the town to promote, collect, trade, and repair old and broken electronics. People can bring out their old cell phones sleeping on their shelves for 3 years to let us e-cycle it, trade it with other electronic, or repair it so you can give it to friends and family members as gifts, or sell on Craigslist.",
                   "How does your concept safeguard human health and protect our environment?",
                   "While conducting research, we were surprised that a recycling center that handles e-cycling already exists in our community! This is a resource that is not being taken advantage of because people are not aware of it and because it is not easy for many people (students who don't have cars for example) to get to. After interviewing the City of Urbana's recycling coordinator, we realized that unless people understand and acknowledge the environment themselves, our effort to encourage people to e-cycle more often would be pointless. What is the purpose of having recycling bin when no one uses it? This was our main idea. Let people know that there is a chance  to protect our environment and provide them an easy way to do it.",
                   "1. What is it? It is a truck, but not just an ordinary truck. E-Cycle Truck promotes about e-cycle by just driving around the town, the truck itself is a great way of promoting the e-cycle! ",
                   "2. When and where? Every Saturday, you can meet this truck at the Lincoln Square at Urbana's farmer's market. Once a month, it will be at the heart of University of Illinois at Urbana Champaign (over 40,000 students from 115 countries), near Illini Union, to provide services. We can also have the truck circulate around campus and the community more regularly and publish its location in real-time on Twitter, similar to how food trucks operate.",
                   "3. How? We provide REPAIRING services, because reusing the electronics, making its e-life to last longer is a better way to save the environment. This way, it saves money, time, and labor that goes into to recycle and produce a new product using it. We COLLECT and TRADE old and broken electronics at a convenience distance. Now people do not have to hold on to their old cellphones or chargers. They can bring it to us and we will safely remove all the personal data in the cellphones and recycle for you.",
                   "4. Who? We are people who like to take a step to save the environment . People who are working for this truck are your friends and your neighbors. You will see friendly faces whenever you visit us.",
                   "5. Why? The main goal of E-Truck is the awareness. We want people to know the importance of e-cycle and to let them know where to bring the ewaste when they actually want to take an action in saving the environment. People will have a convenient means of recycling or repairing their electronics. We provide educational information and guidelines on pamphlets and posters displayed by the truck. It will also be playing videos for people. This truck is ALL about e-cycle. ",
                   "Where does your concept fit into the lifecycle of electronic devices? ",
                   "This concept itself uses a recycled or fixed truck and the services it provides will lengthen the life of electronics by offering repair services as well as offering an easier venue for people to recycle electronics. Right now, people do not really know what's best for the environment. By exposing our E-Truck to people, awareness will be increased. We will educate people and give them an opportunity to reuse their old electronics. We do not just recommend to recycle the electronics but to maximize the life of the products. Also people will no longer hold on to their cellphones, the E-Truck will attract many of \"sleeping in the drawer\" cellphones because now people know where to bring them and do not have to worry about it because the technicians will take care of all their personal data. ",
                   "What steps could be taken today to start implementing your concept? ",
                   "We will contact the City of Champaign and Urbana to discuss more about our idea and ways to get funded. We'll also be contacting local organizations, and University of Illinois for their support, such as advertising the service and getting volunteers. Industrial and graphic designers from DFA UIUC will design the details of the truck. Designers will work on the educational videos, pamphlets, and posters for the truck. We will also talk to computer science/engineering related major students to volunteer to work as technicians for internship credits in return. We also need to find an old truck to use. Because of our repair services, perhaps an old ambulance would be appropriate.",
                   "What kinds of resources will be needed to fully implement and scale your concept?",
                   "1.Money: E-Truck will be getting a financial support through a partnership with the Urbana Recycling Program Center. We have been working with them and they are very interested in this concept and have expressed willingness to sponsor us.",
                   "2.Truck: it can be funded by the city and we can get donations/funding from customers and local organizations to run the truck. We may be able to run a Kickstarter campaign for additional funding.",
                   "3. Interior: We will be using some old monitors that we e-cycled to show educational videos about recycling. We will also have pamphlets and poster and bulletin boards to educate people and to let them know what kind of sources we have here in the town.",
                   "4. Labor: Technicians/drivers can be hired using the advantage of the college town that we are living in, University of Illinois at Urbana-Champaign. They will be computer science/engineering related major students or anyone who is willing to learn basic knowledge of how to handle the electronics can work for us and receive internship credits which will attract many students. Also, there are many homeless in the town and they can be a valuable source of labor. They can work for us and they will get food, clothes, money and other necessities.",
                   "5. Other sources: DFA UIUC will be promoting about the truck online and offline. We will gather bunch of graphic/industrial designers who are members of DFA UIUC to make and attracting posters, and pamphlets and advertise on Social network."],
        likes:      29,
        comments:   24,
        authorName: "DFA UIUC",
        timestamp:  "July 25, 2012, 07:40PM",
        views:      1483,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/e-cycle-truck",
        clicked: false
    },
    {
        openIDEOid: "C-019",
        content: "E-cycling Bin: " +
        "Haven't you thought about it once, \"Why isn't there an e-cycling bin by the dumpster just like recycling bins?\" So we designed it. It is an e-cycling bin for electronics and the stickers for the bin and dumpster inform people about e-cycle.",
        moreInfo:["E-cycling Bin",
                  "Haven't you thought about it once, \"Why isn't there an e-cycling bin by the dumpster just like recycling bins?\" So we designed it. It is an e-cycling bin for electronics and the stickers for the bin and dumpster inform people about e-cycle.",
                  "The purpose of the e-cycling bin is to raise the awareness of community and to let people know that e-cycling electronics is as important as recycling plastic, glass, and paper. It will collect all small to medium size electronics. On the outer surface, we have design a sticker that would go on to the bin and the dumpster. It is to inform them more about the process of e-cycling. We will provide information about where they can e-cycle larger electronics, where are the recycling centers, guidelines on e-cycling, and etc. People will see it everyday and encourage them to e-cycle. ",
                  "How does your concept safeguard human health and protect our environment?",
                  "Many people do not know how to recycle e-cycle, for example, many people have old cell phones that they do not know what to do with.  Or they are too lazy to drive to a recycling center to throw out an old radio. We designed a recycling bin just for e-wastes. It would have informational stickers on it about how to e-cycle properly. We also designed a sticker that would go on a dumpster to remind people that it is illegal to throw out e-waste in the dumpster. This way more people would acknowledge about the importance of the e-cycle.",
                  "Where does your concept fit into the lifecycle of electronic devices? ",
                  "This will increase the number of electronics recycled and properly disassembled. It will give life back to recycled electronics.",
                  "What steps could be taken today to start implementing your concept? ",
                  "We can start with full size model and design the details of the poster. We can contact dumpster company to use our posters. ",
                  "What kinds of resources will be needed to fully implement and scale your concept?",
                  "In order to make it work in real life, we need to partner with community recycling program to provide this service. We will also need to talk to the dumpster company if they are willing to participate in our movement to save the environment. We need some financial support to start making bins and posters."],
        likes:      16,
        comments:   3,
        authorName: "DFA UIUC",
        timestamp:  "July 26, 2012, 07:49PM",
        views:      703,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/e-cycling-bin",
        clicked: false
    },
    {
        openIDEOid: "C-020",
        content: "E-Life Cycled: " +
        "Branding/labeling for 'new' products manufactured substantially with reprocessed materials.",
        moreInfo:["E-Life Cycled",
                  "Branding/labeling for 'new' products manufactured substantially with reprocessed materials.",
                  "Closing the Loop",
                  "We have seen concepts for physically closing the loop which themselves are vitally important, since without them there is no possibility of addressing the problem. Additionally there is enormous value in extending product life, or giving them second life in other hands, but without the final step of recycling the materials from which all these products are made the outcome will not alter.",
                  "Advertising about the possibility of this physical recycling, whether it be attached to the product or conducted through media or education is only one half of the story.",
                  "This concept completes the story by showing to the consumer that their efforts in recycling have had a positive impact - through understanding that the new product in their hands has actually substantially re-used some of the original materials.",
                  "It is important (as a positive feedback mechanism if nothing else) that this is acknowledged.",
                  "Building on Ting-Han Huang's original inspiration for a Brand for \"Made from E-Waste\" and incorporating  Gaby's \"E-Life\" notion (raised initially in Sabine's Pure Tech concept) for renewing and reinvigorating materials from end-of-original-life products.",
                  "I realise that when it comes to branding the logo and slogan are very important but once again lack of visual imagination and marketing/sloganeering skills limits what I can offer - certainly open to any logo/design and slogan contributions from others.",
                  "I simply felt the concept Ting-Han envisioned was too valuable to leave out of the contributions in this concepting phase.",
                  "Would benefit from Marketing Campaigns such as those suggested by Mira Rao and Valentina.",
                  "How does your concept safeguard human health and protect our environment?",
                  "As with other concepts that complete the loop on materials for electrical and electronic products this would substantially contribute to health and environmental well being.",
                  "Where does your concept fit into the lifecycle of electronic devices? ",
                  "Identifying 'new' products as incorporating substantial recycled and reprocessed materials sends a strong message to the consumer as it demonstrates not only the 'possibility' but the fact of reprocessing. It has the potential to alter consumer behaviour because they can see the result of 'positively' recycling these materials.",
                  "Combined with a complementary recycling message it has enormous potential.",
                  "Such a brand/slogan/logo could become as 'everyday' as the concept of biodegradability which, for the time being at least, is a 'feature' of many products throughout the world.",
                  "What steps could be taken today to start implementing your concept? ",
                  "The OpenIDEO community and/or others could develop up the visual and textual components of such an initiative. Someone with advertising and marketing experience could be involved to proof of concept stage."],
        likes:      9,
        comments:   5,
        authorName: "Paul Reader",
        timestamp:  "August 14, 2012, 02:38PM",
        views:      329,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/e-life-cycled",
        clicked: false
    }];
    /*{
        openIdeoid: "C-020",
        content: "install chargers and cords exchange boxes in local stores and shops",
        likes: 37,
        comments: 17,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/chargers-and-cords-exchange-box",
        clicked: false
    },
    {
        openIDEOid: "C-021",
        content: "place QR codes or other identifying markers on electronics that consumers can easily enter into the computer to get convenient instantaneous recommendations for how to recycle (reuse, revamp, repurpose, rent, resell ...) the item in their location.",
        likes: 18,
        comments: 16,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/realtime-recycling-recs",
        clicked: false
    },
    {
        openIDEOid: "C-022",
        content: "Do you know the story of your phone? Where was he born? What is it's age? What is the life expectancy of this phone? In the future will it go to heaven or hell? Get people interested in how their phone effects the environment",
        likes: 36,
        comments: 16,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/the-life-of-your-phone",
        clicked: false
    },
    {
        openIDEOid: "C-023",
        content: "Keep our old devices but still expand our memory and processing by moving to the cloud.",
        likes: 8,
        comments: 16,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/don-t-upgrade-outsource",
        clicked: false
    },
    {
        openIDEOid: "C-024",
        content: "Send old cellphones to recycling facilities in the boxes of their replacements",
        likes: 27,
        comments: 15,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/send-old-cellphones-to-recycling-facilities-in-the-boxes-of-their-replacements",
        clicked: false
    },
    {
        openIDEOid: "C-025",
        content: "Design for disassembly",
        likes: 11,
        comments: 15,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/what-if-we-forgot-what-it-meant-to-201c-own-201d-things-and-became-about-having-it-all-",
        clicked: false
    },
    {
        openIDEOid: "C-026",
        content: "Embed RFID or NFC tags in electronic devices so that e-waste collectors can better manage the waste stream",
        likes: 11,
        comments: 15,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/use-wireless-digital-tags-to-manage-the-waste-stream",
        clicked: false
    },
    {
        openIDEOid: "C-027",
        content: "A service that allows the average joe to be able to go in the nearest coffee shop or local watering hole and get advice on their computer or electronic updates, so they don't have to buy new and can fix their electronics",
        likes: 13,
        comments: 14,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/nerd-share",
        clicked: false
    },
    {
        openIDEOid: "C-028",
        content: "Collect and dismantle e-waste for it's parts (like copper, tin, cobalt, indium, gold, silver ...), and enter it back into the market",
        likes: 17,
        comments: 13,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/golden-e-waste-a-commodity-more-valuable-than-gold-ore",
        clicked: false
    },
    {
        openIDEOid: "C-029",
        content: "People who want to buy a new device could be required to return an old one in order to be granted the right to purchase",
        likes: 5,
        comments: 13,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/buycycle-if-you-want-to-buy-anew-pay-your-due.-or-buy-refurbished-instead.",
        clicked: false
    },
    {
        openIDEOid: "C-030",
        content: "Electronics Trade Club: a website where a particular user may only receive a certain number of electronics. That number can grow if you also send electronics to other users",
        likes: 5,
        comments: 12,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/electronics-trade-club",
        clicked: false
    }];
    {
        content: "Tax electronics based on the time it takes to separate toxic materials containing parts from the rest",
        likes: 7,
        comments: 12,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/disassembly-time-tax",
        clicked: false
    },
    {
        content: "Give students the knowledge they need to design products with recycling, disassembling and resuse in mind.",
        likes: 5,
        comments: 11,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/-teaching-the-green-",
        clicked: false
    },
    {
        content: "Data transfer and elimination services will encourage users to hand in their old phones to be re-used, re-furbished or re-cycled without having to worry that personal data is either lost or misused.",
        likes: 32,
        comments: 11,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/digital-data-transfer-and-elimination-service-",
        clicked: false
    },
    {
        content: "Modeled after restaurants with calories on the menus, electronics can be similarly assigned an 'e-rating' for customers to see",
        likes: 12,
        comments: 11,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/e-rating-a-lesson-from-fast-food-menus",
        clicked: false
    },
    {
        content: "Standardize how recycling centers recycle materials from old electronics",
        likes: 2,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/track-the-bulk-flow",
        clicked: false
    },
    {
        content: "How about taking apart discarded electronics and building a library of real exploded items?",
        likes: 5,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/explode-em",
        clicked: false
    },
    {
        content: "Pulverize the nonbiodegradable (and often, hardly reusable) e-waste into a fine powder and mix that product with an epoxy resin, then shape it into bricks to use as building materials.",
        likes: 8,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/don-t-debate-granulate-turning-e-waste-into-rugged-building-materials",
        clicked: false
    },
    {
        content: "Turning e-waste into a social business",
        likes: 8,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/turning-e-waste-into-a-social-business",
        clicked: false
    },
    {
        content: "Create a college course about sustainable consumption and make it mandatory for all college students",
        likes: 8,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/teach-college-students-about-sustainable-consumption",
        clicked: false
    },
    {
        content: "Special limited edition e-devices with special features will incentivize owners to keep and maintain the products for a longer period of time rather than trashing an item in favor of the lastest and greatest gadget",
        likes: 6,
        comments: 10,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/limited-edition-products-to-encourage-owners-to-maintain-not-trash-e-devices",
        clicked: false
    },
    {
        content: "Include in all new electronics packages a flier that describes the e-waste issue and exactly what the consumer should do witht he old product they are replacing. The back of the flier will be a prepaid packing slip to send the e-waste to a recycler.",
        likes: 5,
        comments: 9,
        url: "https://challenges.openideo.com/challenge/e-waste/concepting/educate-the-exact-population-that-is-about-to-e-waste",
        clicked: false
}];*/

function getRandom(min, max){
    return Math.floor((Math.random() * max) + min);
}

if(Ideas.find().count() === 0){
    for(i = 0; i < ideaData.length; i++){
        Ideas.insert(ideaData[i]);
    }
}